-- =============================================================
-- Description: init user & plugin modules (users/plugin registry/config/grants)
-- Tables     : users, user_settings, llm_providers, pet_settings, plugins, plugin_tools, plugin_configs, plugin_grants
-- Doc        : docs/database.md section 2.1, 2.2
-- Generated by tools/extract-ddl.ps1 - extracted from docs/database.md
-- 修改表结构：先改 docs/database.md，再重跑 tools/extract-ddl.ps1 生成新版本文件
-- =============================================================

CREATE TABLE `users` (
  `id`            BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `username`      VARCHAR(64)  NOT NULL                COMMENT '登录名，本地单用户时固定为 local',
  `display_name`  VARCHAR(64)  NOT NULL DEFAULT '学习者' COMMENT '显示名，用于桌宠称呼与 AI 提示',
  `avatar_path`   VARCHAR(255)     NULL                COMMENT '头像相对路径，NULL 表示使用大肥鱼默认形象',
  `status`        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/DISABLED',
  `last_login_at` DATETIME(3)      NULL                COMMENT '最近登录时间(UTC)',
  `created_at`    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  `deleted_at`    DATETIME(3)  NOT NULL DEFAULT '1970-01-01 00:00:00.000' COMMENT '软删除时间(UTC)，默认值表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_username` (`username`, `deleted_at`),
  CONSTRAINT `ck_users_status` CHECK (`status` IN ('ACTIVE','DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';

CREATE TABLE `user_settings` (
  `id`             BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id`        BIGINT       NOT NULL                COMMENT '所属用户ID，逻辑外键 users.id',
  `setting_key`    VARCHAR(64)  NOT NULL                COMMENT '设置项键，如 theme/language/active_provider_id',
  `setting_value`  TEXT             NULL                COMMENT '设置项值(JSON 或纯文本)，敏感值必须先加密',
  `value_type`     VARCHAR(16)  NOT NULL DEFAULT 'STRING' COMMENT '值类型：STRING/INT/BOOL/JSON',
  `is_secret`      TINYINT(1)   NOT NULL DEFAULT 0      COMMENT '是否密文：1=需解密后使用',
  `created_at`     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_settings_user_key` (`user_id`, `setting_key`),
  CONSTRAINT `ck_user_settings_value_type` CHECK (`value_type` IN ('STRING','INT','BOOL','JSON'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户级键值设置表';

CREATE TABLE `llm_providers` (
  `id`                BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id`           BIGINT        NOT NULL                COMMENT '所属用户ID，逻辑外键 users.id',
  `provider_code`     VARCHAR(64)   NOT NULL                COMMENT '供应商标识：deepseek/openai/ollama/azure-openai 等',
  `display_name`      VARCHAR(64)   NOT NULL                COMMENT '展示名，如 DeepSeek 官方',
  `base_url`          VARCHAR(255)      NULL                COMMENT 'API Base URL，NULL 表示用 SDK 默认',
  `default_model`     VARCHAR(64)       NULL                COMMENT '默认模型名，如 deepseek-chat',
  `api_key_cipher`    VARBINARY(512)    NULL                COMMENT 'API Key 的 AES-256-GCM 密文，禁止明文',
  `api_key_hint`      VARCHAR(16)       NULL                COMMENT 'Key 尾部提示(如 sk-***abcd)，仅用于 UI 回显',
  `is_enabled`        TINYINT(1)    NOT NULL DEFAULT 1      COMMENT '是否启用：1=启用，0=停用',
  `is_default`        TINYINT(1)    NOT NULL DEFAULT 0      COMMENT '是否默认供应商：1=默认，同一用户最多一个',
  `temperature`       DECIMAL(3,2)  NOT NULL DEFAULT 0.70   COMMENT '默认温度参数',
  `max_tokens`        INT               NULL                COMMENT '默认最大输出 token，NULL 表示由模型决定',
  `timeout_seconds`   INT           NOT NULL DEFAULT 60     COMMENT '请求超时秒数',
  `last_tested_at`    DATETIME(3)       NULL                COMMENT '最近一次连通性测试时间(UTC)',
  `last_test_result`  VARCHAR(255)      NULL                COMMENT '最近一次测试结果摘要(不含敏感信息)',
  `created_at`        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  `deleted_at`        DATETIME(3)   NOT NULL DEFAULT '1970-01-01 00:00:00.000' COMMENT '软删除时间(UTC)，默认值表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_llm_providers_user_code` (`user_id`, `provider_code`, `deleted_at`),
  KEY `idx_llm_providers_user_enabled` (`user_id`, `is_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LLM 供应商与 API 配置表';

CREATE TABLE `pet_settings` (
  `id`                   BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id`              BIGINT       NOT NULL                COMMENT '所属用户ID，逻辑外键 users.id',
  `window_x`             DECIMAL(12,2) NOT NULL DEFAULT 0     COMMENT '桌宠窗口 X 坐标(虚拟桌面像素)',
  `window_y`             DECIMAL(12,2) NOT NULL DEFAULT 0     COMMENT '桌宠窗口 Y 坐标(虚拟桌面像素)',
  `window_scale`         DECIMAL(4,3) NOT NULL DEFAULT 1.000  COMMENT '缩放比例，如 1.000 / 0.750',
  `always_on_top`        TINYINT(1)   NOT NULL DEFAULT 1      COMMENT '是否窗口置顶：1=置顶',
  `click_through`        TINYINT(1)   NOT NULL DEFAULT 0      COMMENT '是否鼠标穿透：1=穿透',
  `pet_size`             VARCHAR(16)  NOT NULL DEFAULT 'MEDIUM' COMMENT '显示尺寸档：SMALL/MEDIUM/LARGE',
  `opacity`              DECIMAL(4,3) NOT NULL DEFAULT 1.000  COMMENT '整体不透明度 0.000-1.000',
  `sound_enabled`        TINYINT(1)   NOT NULL DEFAULT 1      COMMENT '是否开启音效',
  `animation_enabled`    TINYINT(1)   NOT NULL DEFAULT 1      COMMENT '是否开启动画',
  `animation_fps`        TINYINT      NOT NULL DEFAULT 30     COMMENT '动画帧率上限',
  `idle_sleep_seconds`   INT          NOT NULL DEFAULT 600    COMMENT '无操作多少秒后进入睡眠状态(状态 sleep)',
  `proactive_enabled`    TINYINT(1)   NOT NULL DEFAULT 0      COMMENT '是否开启主动提醒，默认关闭(少打扰原则)',
  `proactive_min_interval_seconds` INT NOT NULL DEFAULT 3600  COMMENT '主动提醒最小间隔秒数，防止频繁打扰',
  `quiet_hours_start`    TIME             NULL                COMMENT '免打扰开始时间(本地时间)，NULL 表示不限制',
  `quiet_hours_end`      TIME             NULL                COMMENT '免打扰结束时间(本地时间)，NULL 表示不限制',
  `created_at`           DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`           DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pet_settings_user` (`user_id`),
  CONSTRAINT `ck_pet_settings_pet_size` CHECK (`pet_size` IN ('SMALL','MEDIUM','LARGE')),
  CONSTRAINT `ck_pet_settings_opacity` CHECK (`opacity` >= 0 AND `opacity` <= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='桌宠偏好设置表';

CREATE TABLE `plugins` (
  `id`             BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
  `plugin_key`     VARCHAR(64)   NOT NULL                COMMENT '插件唯一标识，如 pomodoro/note/wrong-question',
  `name`           VARCHAR(64)   NOT NULL                COMMENT '插件名称(展示用)',
  `version`        VARCHAR(32)   NOT NULL                COMMENT '插件版本，语义化版本如 1.0.0',
  `author`         VARCHAR(64)       NULL                COMMENT '插件作者',
  `description`    VARCHAR(500)      NULL                COMMENT '插件描述',
  `entry_point`    VARCHAR(255)      NULL                COMMENT '入口标识，如 Spring Bean 名或前端入口路径',
  `capabilities`   JSON              NULL                COMMENT '能力声明 JSON 数组，如 ["timer","stats"]',
  `dependencies`   JSON              NULL                COMMENT '依赖的其他插件 key 数组',
  `required_permissions` JSON         NULL               COMMENT '插件声明的必需权限 JSON 数组',
  `status`         VARCHAR(16)   NOT NULL DEFAULT 'DISABLED' COMMENT '状态：ENABLED/DISABLED/ERROR',
  `installed_at`   DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '安装/注册时间(UTC)',
  `last_loaded_at` DATETIME(3)       NULL                COMMENT '最近一次加载成功时间(UTC)',
  `load_error`     VARCHAR(500)      NULL                COMMENT '最近一次加载失败原因，成功时置 NULL',
  `created_at`     DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`     DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  `deleted_at`     DATETIME(3)   NOT NULL DEFAULT '1970-01-01 00:00:00.000' COMMENT '软删除时间(UTC)，默认值表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugins_key_version` (`plugin_key`, `version`, `deleted_at`),
  KEY `idx_plugins_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='插件注册表';

CREATE TABLE `plugin_tools` (
  `id`                  BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `plugin_id`           BIGINT       NOT NULL                COMMENT '所属插件ID，逻辑外键 plugins.id',
  `tool_name`           VARCHAR(64)  NOT NULL                COMMENT '工具名(全局唯一)，如 getLearningStats',
  `display_name`        VARCHAR(64)      NULL                COMMENT '工具展示名',
  `description`         VARCHAR(500)     NULL                COMMENT '给 LLM 看的工具描述，直接影响调用准确率',
  `input_schema`        JSON             NULL                COMMENT '入参 JSON Schema',
  `output_schema`       JSON             NULL                COMMENT '出参 JSON Schema',
  `required_permission` VARCHAR(32)      NULL                COMMENT '调用所需权限码，NULL 表示无需额外权限',
  `is_enabled`          TINYINT(1)   NOT NULL DEFAULT 1      COMMENT '是否启用：1=启用',
  `created_at`          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugin_tools_name` (`tool_name`),
  KEY `idx_plugin_tools_plugin` (`plugin_id`, `is_enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='插件对外暴露的 Tool 注册表';

CREATE TABLE `plugin_configs` (
  `id`             BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `plugin_id`      BIGINT       NOT NULL                COMMENT '所属插件ID，逻辑外键 plugins.id',
  `user_id`        BIGINT       NOT NULL                COMMENT '生效用户ID，逻辑外键 users.id(为多用户留余地)',
  `config_key`     VARCHAR(64)  NOT NULL                COMMENT '配置键，如 default_focus_minutes',
  `config_value`   TEXT             NULL                COMMENT '配置值(字符串化，复杂结构用 JSON)',
  `value_type`     VARCHAR(16)  NOT NULL DEFAULT 'STRING' COMMENT '值类型：STRING/INT/BOOL/JSON',
  `is_secret`      TINYINT(1)   NOT NULL DEFAULT 0      COMMENT '是否密文：1=需解密后使用',
  `created_at`     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugin_configs_scope_key` (`plugin_id`, `user_id`, `config_key`),
  CONSTRAINT `ck_plugin_configs_value_type` CHECK (`value_type` IN ('STRING','INT','BOOL','JSON'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='插件配置表';

CREATE TABLE `plugin_grants` (
  `id`              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `plugin_id`       BIGINT       NOT NULL                COMMENT '插件ID，逻辑外键 plugins.id',
  `user_id`         BIGINT       NOT NULL                COMMENT '授权用户ID，逻辑外键 users.id',
  `permission_code` VARCHAR(32)  NOT NULL                COMMENT '权限码：READ/WRITE/NETWORK/FILE/SYSTEM/AI',
  `status`          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE' COMMENT '授权状态：ACTIVE/REVOKED/DENIED',
  `granted_by`      VARCHAR(16)  NOT NULL DEFAULT 'USER' COMMENT '授权来源：USER=用户手动确认/SYSTEM=默认授予',
  `granted_at`      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '授权时间(UTC)',
  `revoked_at`      DATETIME(3)      NULL                COMMENT '撤销时间(UTC)，NULL 表示未撤销',
  `created_at`      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugin_grants_scope_perm` (`plugin_id`, `user_id`, `permission_code`),
  KEY `idx_plugin_grants_user_status` (`user_id`, `status`),
  CONSTRAINT `ck_plugin_grants_permission` CHECK (`permission_code` IN ('READ','WRITE','NETWORK','FILE','SYSTEM','AI')),
  CONSTRAINT `ck_plugin_grants_status` CHECK (`status` IN ('ACTIVE','REVOKED','DENIED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='插件权限授权记录表';
