-- =============================================================
-- Description: init learning module (goals/tasks/sessions/daily aggregation)
-- Tables     : study_goals, study_tasks, learning_sessions, learning_session_daily
-- Doc        : docs/database.md section 2.3
-- Generated by tools/extract-ddl.ps1 - extracted from docs/database.md
-- 修改表结构：先改 docs/database.md，再重跑 tools/extract-ddl.ps1 生成新版本文件
-- =============================================================

CREATE TABLE `study_goals` (
  `id`               BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id`          BIGINT       NOT NULL                COMMENT '所属用户ID，逻辑外键 users.id',
  `title`            VARCHAR(128) NOT NULL                COMMENT '目标标题，如 三个月内掌握 Redis 核心原理',
  `description`      VARCHAR(500)     NULL                COMMENT '目标描述',
  `goal_type`        VARCHAR(16)  NOT NULL DEFAULT 'LONG_TERM' COMMENT '目标类型：SHORT_TERM/LONG_TERM',
  `status`           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/COMPLETED/ARCHIVED',
  `target_value`     INT              NULL                COMMENT '目标量化值，如 3600(秒) 或 30(天)',
  `current_value`    INT          NOT NULL DEFAULT 0      COMMENT '当前进度值，由学习事件更新',
  `unit`             VARCHAR(16)      NULL                COMMENT '量化单位：SECONDS/DAYS/COUNT',
  `start_date`       DATE             NULL                COMMENT '开始日期(本地业务日)',
  `due_date`         DATE             NULL                COMMENT '截止日期(本地业务日)',
  `completed_at`     DATETIME(3)      NULL                COMMENT '完成时间(UTC)',
  `created_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  `deleted_at`       DATETIME(3)  NOT NULL DEFAULT '1970-01-01 00:00:00.000' COMMENT '软删除时间(UTC)，默认值表示未删除',
  PRIMARY KEY (`id`),
  KEY `idx_study_goals_user_status` (`user_id`, `status`, `deleted_at`),
  KEY `idx_study_goals_user_due` (`user_id`, `due_date`),
  CONSTRAINT `ck_study_goals_type` CHECK (`goal_type` IN ('SHORT_TERM','LONG_TERM')),
  CONSTRAINT `ck_study_goals_status` CHECK (`status` IN ('ACTIVE','COMPLETED','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='学习目标表';

CREATE TABLE `study_tasks` (
  `id`                 BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id`            BIGINT       NOT NULL                COMMENT '所属用户ID，逻辑外键 users.id',
  `goal_id`            BIGINT           NULL                COMMENT '所属目标ID，逻辑外键 study_goals.id，NULL 表示独立任务',
  `title`              VARCHAR(128) NOT NULL                COMMENT '任务标题',
  `subject`            VARCHAR(64)      NULL                COMMENT '学科/科目，如 Redis、MySQL',
  `status`             VARCHAR(16)  NOT NULL DEFAULT 'TODO' COMMENT '状态：TODO/DOING/DONE/CANCELLED',
  `priority`           TINYINT      NOT NULL DEFAULT 2      COMMENT '优先级：1=高 2=中 3=低',
  `plan_date`          DATE             NULL                COMMENT '计划执行日期(本地业务日)',
  `duration_plan_seconds` INT           NULL                COMMENT '计划时长(秒)',
  `duration_done_seconds` INT       NOT NULL DEFAULT 0      COMMENT '已完成时长(秒)，由学习会话结束事件累加',
  `sort_order`         INT          NOT NULL DEFAULT 0      COMMENT '同日期内排序序号',
  `completed_at`       DATETIME(3)      NULL                COMMENT '完成时间(UTC)',
  `created_at`         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  `deleted_at`         DATETIME(3)  NOT NULL DEFAULT '1970-01-01 00:00:00.000' COMMENT '软删除时间(UTC)，默认值表示未删除',
  PRIMARY KEY (`id`),
  KEY `idx_study_tasks_user_status_plan` (`user_id`, `status`, `plan_date`, `deleted_at`),
  KEY `idx_study_tasks_goal` (`goal_id`),
  CONSTRAINT `ck_study_tasks_status` CHECK (`status` IN ('TODO','DOING','DONE','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='学习任务表';

CREATE TABLE `learning_sessions` (
  `id`                    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `client_session_uid`    CHAR(36)     NOT NULL                COMMENT '客户端生成的会话UUID，用于离线补传去重',
  `idempotency_key`       VARCHAR(64)  NOT NULL                COMMENT '幂等键，服务端唯一，重复写入被丢弃',
  `user_id`               BIGINT       NOT NULL                COMMENT '所属用户ID，逻辑外键 users.id',
  `plugin_key`            VARCHAR(64)  NOT NULL DEFAULT 'pomodoro' COMMENT '产生本次会话的插件 key',
  `task_id`               BIGINT           NULL                COMMENT '关联学习任务ID，逻辑外键 study_tasks.id',
  `knowledge_point_id`    BIGINT           NULL                COMMENT '关联知识点ID，逻辑外键 knowledge_points.id',
  `subject`               VARCHAR(64)      NULL                COMMENT '学科/主题，如 Redis',
  `session_type`          VARCHAR(16)  NOT NULL DEFAULT 'POMODORO' COMMENT '会话类型：POMODORO/FREE/REVIEW',
  `status`                VARCHAR(16)  NOT NULL DEFAULT 'RUNNING' COMMENT '状态：RUNNING/COMPLETED/ABORTED',
  `duration_seconds`      INT          NOT NULL DEFAULT 0      COMMENT '有效学习时长(秒)',
  `focused_seconds`       INT          NOT NULL DEFAULT 0      COMMENT '其中处于专注状态的时长(秒)',
  `paused_seconds`        INT          NOT NULL DEFAULT 0      COMMENT '暂停累计时长(秒)',
  `pause_count`           INT          NOT NULL DEFAULT 0      COMMENT '暂停次数',
  `interruption_count`    INT          NOT NULL DEFAULT 0      COMMENT '打断次数(切窗口/离开等)',
  `focus_score`           TINYINT          NULL                COMMENT '专注评分 0-100，由插件计算',
  `started_at`            DATETIME(3)  NOT NULL                COMMENT '开始时间(UTC)',
  `ended_at`              DATETIME(3)      NULL                COMMENT '结束时间(UTC)，RUNNING 时为 NULL',
  `started_ts`            BIGINT       NOT NULL                COMMENT '开始时间戳(epoch millis)，供桌宠动画对齐',
  `ended_ts`              BIGINT           NULL                COMMENT '结束时间戳(epoch millis)',
  `stat_date`             DATE         NOT NULL                COMMENT '归属业务日期(本地)，用于按天聚合，跨零点会话归开始日',
  `mood`                  VARCHAR(16)      NULL                COMMENT '学习后自评：GREAT/NORMAL/TIRED/BAD',
  `remark`                VARCHAR(500)     NULL                COMMENT '用户备注',
  `created_at`            DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`            DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ls_idempotency_key` (`idempotency_key`),
  UNIQUE KEY `uk_ls_client_uid` (`client_session_uid`),
  KEY `idx_ls_user_started` (`user_id`, `started_at`),
  KEY `idx_ls_user_statdate_status` (`user_id`, `stat_date`, `status`),
  KEY `idx_ls_user_subject` (`user_id`, `subject`),
  KEY `idx_ls_knowledge_point` (`knowledge_point_id`),
  KEY `idx_ls_task` (`task_id`),
  CONSTRAINT `ck_ls_session_type` CHECK (`session_type` IN ('POMODORO','FREE','REVIEW')),
  CONSTRAINT `ck_ls_status` CHECK (`status` IN ('RUNNING','COMPLETED','ABORTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='学习会话表(番茄钟)';

CREATE TABLE `learning_session_daily` (
  `id`                   BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id`              BIGINT       NOT NULL                COMMENT '所属用户ID，逻辑外键 users.id',
  `stat_date`            DATE         NOT NULL                COMMENT '统计业务日期(本地)',
  `session_count`        INT          NOT NULL DEFAULT 0      COMMENT '会话次数',
  `total_seconds`        INT          NOT NULL DEFAULT 0      COMMENT '当日总学习时长(秒)',
  `focused_seconds`      INT          NOT NULL DEFAULT 0      COMMENT '当日专注时长(秒)',
  `pomodoro_count`       INT          NOT NULL DEFAULT 0      COMMENT '完成的番茄钟个数',
  `question_count`       INT          NOT NULL DEFAULT 0      COMMENT '当日答题数',
  `correct_count`        INT          NOT NULL DEFAULT 0      COMMENT '当日答对数',
  `wrong_count`          INT          NOT NULL DEFAULT 0      COMMENT '当日答错数',
  `note_count`           INT          NOT NULL DEFAULT 0      COMMENT '当日新建笔记数',
  `new_knowledge_count`  INT          NOT NULL DEFAULT 0      COMMENT '当日新学知识点数',
  `review_count`         INT          NOT NULL DEFAULT 0      COMMENT '当日复习次数',
  `total_hours`          DECIMAL(10,2) NOT NULL DEFAULT 0.00  COMMENT '当日总时长(小时)，展示用冗余',
  `first_started_at`     DATETIME(3)      NULL                COMMENT '当日首次开始学习时间(UTC)',
  `last_ended_at`        DATETIME(3)      NULL                COMMENT '当日最后一次结束学习时间(UTC)',
  `created_at`           DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`           DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_lsd_user_date` (`user_id`, `stat_date`),
  KEY `idx_lsd_date` (`stat_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每日学习统计预聚合表';
