-- =============================================================
-- Description: Phase 7 (RAG) vector tables - NOT applied during MVP
-- Tables     : vector_collections, vector_chunks
-- Doc        : docs/database.md section 8.3
-- Generated by tools/extract-ddl.ps1 - extracted from docs/database.md
-- 修改表结构：先改 docs/database.md，再重跑 tools/extract-ddl.ps1 生成新版本文件
-- =============================================================

CREATE TABLE `vector_collections` (
  `id`              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `collection_name` VARCHAR(128) NOT NULL COMMENT '向量库集合名，如 notes_kp_v1',
  `embedding_model` VARCHAR(64)  NOT NULL COMMENT 'Embedding 模型名',
  `dimension`       INT          NOT NULL COMMENT '向量维度',
  `chunk_size`      INT          NOT NULL DEFAULT 512 COMMENT '切分块大小(token)',
  `chunk_overlap`   INT          NOT NULL DEFAULT 64  COMMENT '切分重叠(token)',
  `is_active`       TINYINT(1)   NOT NULL DEFAULT 1   COMMENT '是否启用',
  `created_at`      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  `updated_at`      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_vc_name` (`collection_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='向量集合登记表(Phase 7)';

-- 届时新增：向量化片段与业务对象的映射（外部向量库只存向量，映射留 MySQL）

CREATE TABLE `vector_chunks` (
  `id`                 BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  `collection_id`      BIGINT       NOT NULL COMMENT '所属集合ID，逻辑外键 vector_collections.id',
  `source_type`        VARCHAR(32)  NOT NULL COMMENT '来源类型：NOTE/KNOWLEDGE_POINT/QUESTION/PLUGIN_DOC',
  `source_id`          BIGINT       NOT NULL COMMENT '来源对象ID',
  `chunk_index`        INT          NOT NULL DEFAULT 0 COMMENT '同一来源内的切分序号',
  `chunk_text`         TEXT         NOT NULL COMMENT '切分后的原文片段(便于回溯与重建)',
  `external_vector_id` VARCHAR(128) NOT NULL COMMENT '外部向量库中的ID',
  `created_at`         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间(UTC)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_vchunk_source` (`collection_id`, `source_type`, `source_id`, `chunk_index`),
  KEY `idx_vchunk_source_obj` (`source_type`, `source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='向量片段映射表(Phase 7)';
